server.port=8080
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_8s1C4HVWpO1vyHY0Iuc@banking-app-db-dattaram-muknak.e.aivencloud.com:11932/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_8s1C4HVWpO1vyHY0Iuc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
